- hosts: localhost
  connection: local
  pre_tasks:
    - name: add repositories
      become: true
      apt_repository:
        repo: "{{item}}"
        state: present
      with_items:
        - ppa:git-core/ppa
        - ppa:embrosyn/cinnamon

    - name: update repositories
      become: true
      apt: update_cache=yes
      changed_when: False

  tasks:
    - include: tasks/git.yml
    - include: tasks/packages.yml
    - include: tasks/download.extract.yml
    - include: tasks/python.yml
    - include: tasks/bashrc.yml
    - include: tasks/copy.config.files.yml
