- hosts: localhost
  connection: local
  pre_tasks:
    - name: add repositories
      become: true
      apt_repository:
        repo: ppa:git-core/ppa
        state: present

    - name: update repositories
      become: true
      apt: update_cache=yes
      changed_when: False

  tasks:
    - include: tasks/copy.config.files.yml
    - include: tasks/packages.yml
    - include: tasks/download.extract.yml
