- name: copy files
  copy:
    src=config-files/.bash_aliases
    dest="{{ansible_user_dir}}/.bash_aliases"
    force=no
    mode=preserve
  copy:
    src=config-files/Preferences.sublime-settings
    dest={{ansible_user_dir}}/.config/sublime-text-3/Packages/User/Preferences.sublime-settings
    force=no
    mode=preserve
