- name: Install Bcftools
  block:
    # Download and uncompress Bcftools
    - unarchive:
        src="https://github.com/samtools/bcftools/releases/download/1.8/bcftools-1.8.tar.bz2"
        dest="{{ansible_user_dir}}/software"
        creates="{{ansible_user_dir}}/software/bcftools-1.8"
        copy=no
    - make:
        chdir: "{{ansible_user_dir}}/software/bcftools-1.8"
    # Add Bcftools to path in .bashrc if it does not exist
    - lineinfile:
        path: ~/.bashrc
        line: "export PATH=$PATH:~/software/bcftools-1.8"

- name: Install htslib (bgzip and tabix)
  block:
    # Download and uncompress htslib
    - unarchive:
        src="https://github.com/samtools/htslib/releases/download/1.8/htslib-1.8.tar.bz2"
        dest="{{ansible_user_dir}}/software"
        creates="{{ansible_user_dir}}/software/htslib-1.8"
        copy=no
    - make:
        chdir: "{{ansible_user_dir}}/software/htslib-1.8"
    - make:
        chdir: "{{ansible_user_dir}}/software/htslib-1.8"
        target: install
      become: yes

- name: Install Mugsy
  block:
    # Download and uncompress Mugsy
    - unarchive:
        src="https://sourceforge.net/projects/mugsy/files/mugsy_x86-64-v1r2.3.tgz/download"
        dest="{{ansible_user_dir}}/software"
        creates="{{ansible_user_dir}}/software/mugsy_x86-64-v1r2.3"
        copy=no
    # Update Mugsy env script -- replace existing line
    - lineinfile:
        path: "{{ansible_user_dir}}/software/mugsy_x86-64-v1r2.3/mugsyenv.sh"
        line: "export MUGSY_INSTALL={{ansible_user_dir}}/software/mugsy_x86-64-v1r2.3"
        regexp: "export MUGSY_INSTALL"
    # Add Mugsy env script to .bashrc if it does not exist
    - blockinfile:
        path: ~/.bashrc
        block: |
          # Mugsy
          source ~/software/mugsy_x86-64-v1r2.3/mugsyenv.sh

- name: Install Muscle
  block:
    # Create Muscle dest directory
    - file:
        path: "{{ansible_user_dir}}/software/muscle3.8.31"
        state: directory
        recurse: yes
    # Download and uncompress Muscle
    - unarchive:
        src="https://www.drive5.com/muscle/downloads3.8.31/muscle3.8.31_i86linux64.tar.gz"
        dest="{{ansible_user_dir}}/software/muscle3.8.31"
        creates="{{ansible_user_dir}}/software/muscle3.8.31/muscle3.8.31_i86linux64"
        copy=no
    # Create "muscle" symlink
    - file:
        src: "muscle3.8.31_i86linux64"
        dest: "{{ansible_user_dir}}/software/muscle3.8.31/muscle"
        state: link
    # Add Muscle to path in .bashrc if it does not exist
    - lineinfile:
        path: ~/.bashrc
        line: "export PATH=$PATH:~/software/muscle3.8.31"

- name: Install Samtools
  block:
    # Download and uncompress Samtools
    - unarchive:
        src="https://sourceforge.net/projects/samtools/files/samtools/1.4/samtools-1.4.tar.bz2"
        dest="{{ansible_user_dir}}/software"
        creates="{{ansible_user_dir}}/software/samtools-1.4"
        copy=no
    - unarchive:
        src="https://sourceforge.net/projects/samtools/files/samtools/1.8/samtools-1.8.tar.bz2"
        dest="{{ansible_user_dir}}/software"
        creates="{{ansible_user_dir}}/software/samtools-1.8"
        copy=no
    - make:
        chdir: "{{ansible_user_dir}}/software/samtools-1.4"
    - make:
        chdir: "{{ansible_user_dir}}/software/samtools-1.8"
    # Add Samtools to path in .bashrc if it does not exist
    - lineinfile:
        path: ~/.bashrc
        line: "export PATH=$PATH:~/software/samtools-1.8:~/software/samtools-1.8/misc"

