- name: Install packages
  package:
    name: "{{item}}"
    state: latest
  with_items:
    - apt-file
    - atop
    - dos2unix
    - htop
    - iotop
    - gitk
    - gparted
    - kdiff3
    - mafft
    - meld
    - python-dev
    - shunit2
    - snp-sites
    - sysstat
    - tree
    - gnumeric
