- name: Install python versions
  shell: . {{ansible_user_dir}}/.bashrc && pyenv install {{ item }}
    creates="{{ansible_user_dir}}/.pyenv/versions/{{ item }}"
  with_items:
    - 2.6.9
    - 2.7.15
    - 3.3.7
    - 3.4.9
    - 3.5.6
    - 3.6.8
    - 3.7.2
